sudo: true
language: clojure
before_deploy: lein uberjar
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: tools@sap.com
  password:
    secure: SbAORvg/ANEo0SoawmDmay0d/0NfWUK81Qhr74YMD5MNeMl/ruv3iqtr5DjgCxTRSv+g1Hp2AlQqyx3ORsxd3yvAAHfxxEUQFexEETxX7qm7Maq9t1BNGoTfrSDPGufmlDJHJjFIe8CnQ7HPnRaAkEEy8mGDFG+Rnc7U1DbOGTM=
  organization: GithubTeam
  space: applications
  on:
    repo: reviewninja/reviewninja-slack
