sudo: true
language: clojure
before_script: lein deps
script: lein test
deploy:
  edge: true
  provider: cloudfoundry
  username: tools@sap.com
  password:
    secure: CQ8wPtDpkxNL3F7vrpaDTCOZS68c7d7TKXyH3ql7DEBpdYq6ETSyhiw8kxiX42ethPd6OFGMcdZRKIkOqH5qtpkwjGbFhBswNqfEzoWrjk/1/JUPLiTbAgkNdIl1uaF6ON6pIEQJOCkCD/GiTchxIatQPYWqtaRD/OTPiJ12AiM=
  api: https://api.run.pivotal.io
  organization: GithubTeam
  space: applications
