sudo: true
language: clojure
before_script: lein deps
script: lein test
deploy:
  edge: true
  provider: cloudfoundry
  username: tools@sap.com
  password:
    secure: gOcDwPbY3JIEt6DJT93U2GExvQZhA9+vYDcIqe8Q+Dy2c0an6JOD7EWK5r64vcMDatdWRpaFwkSQBWjAFyJX9L97FvBnEGbjyGEo75geNPs+QkBwIqVsgohZXAARfFEZpCo23b2+z8Whtz2zhwX7BinW1kZad7TcZ3zIIQZVrWw=
  api: https://api.run.pivotal.io
  organization: GithubTeam
  space: applications
